responsavel=input("Nome do responsável:")
funcionario=input("Nome do funcionário:")
evento=input("Digite o nome do evento: ")
valor=float(input("Digite o valor que será recebido de volta: "))
print("Declaro para o senhor " + responsavel+ ", que o senhor " + funcionario + " esteve presente no evento " + evento + " e gastou o valor de R$ " + str(valor) + " com a entrada.")